---
title: "R E10 Volcano plots"
output:
  html_document:
    df_print: paged
  github_document: default
---


```{r libraries}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(EnhancedVolcano)
  library(ggsci)
  library(openxlsx)
})
```

```{r readdata}
seurat <- readRDS(file = "../data/HB10hpf_neural.RDS")
DefaultAssay(seurat) <- "SCT"
Idents(seurat) <- "Clusters"
DimPlot(seurat, reduction = "wnn.umap") + scale_color_igv()
```
```{r rename}
Idents(seurat) <- "Clusters"
seurat <- RenameIdents(seurat,
                       "CaudHB.1" = "CHB",
                       "CaudHB.2" = "CHB",
                       "CaudHB.3" = "CHB",
                       "SC.1" = "SC",
                       "SC.2" = "SC",
                       "SC.3" = "SC")
DimPlot(seurat, reduction = "wnn.umap") + scale_color_igv()
```


```{r SCvsr6}
markers.SCvsHB2 <- FindMarkers(seurat, ident.1 = "SC", ident.2 = "HB.2", verbose = F, recorrect_umi = F)
markers.SCvsHB2
```

```{r SCvsCHB}
markers.SCvsCHB <- FindMarkers(seurat, ident.1 = "SC", ident.2 = "CHB", verbose = F, recorrect_umi = F)
markers.SCvsCHB
```

```{r r6vsCHB}
markers.HB2vsCHB <- FindMarkers(seurat, ident.1 = "HB.2", ident.2 = "CHB", verbose = F, recorrect_umi = F)
markers.HB2vsCHB
```

```{r SCvsr6plot, fig.width=7, fig.height=5}
keyvals <- ifelse(
   markers.SCvsHB2$avg_log2FC < -0.5 & markers.SCvsHB2$p_val_adj < 0.05, 'blue3',
   ifelse(markers.SCvsHB2$avg_log2FC > 0.5 & markers.SCvsHB2$p_val_adj < 0.05, 'orange2',
   'grey50'))
keyvals[is.na(keyvals)]<-'grey50'
names(keyvals)[keyvals == 'blue3'] <- 'Up-regulated HB.2'
names(keyvals)[keyvals == 'orange2'] <- 'Up-regulated SC'
names(keyvals)[keyvals == 'grey50'] <- 'Not significant'

p1 <- EnhancedVolcano(markers.SCvsHB2 , 
                rownames(markers.SCvsHB2 ),
                x ="avg_log2FC", 
                y ="p_val_adj",
                pCutoff = 0.05,
                FCcutoff = 0.5,
                title = "Volcano plot SC vs HB.2",
                legendPosition = "right",
                lab = NA,
                subtitle = NULL,
                gridlines.minor = FALSE, gridlines.major = FALSE,
                #selectLab = rownames(markers.SCvsr6[which(names(keyvals) %in% c('Down-regulated','Up-regulated'))]),
                colCustom = keyvals)
p1
```


```{r SCvsCHBplot, fig.width=7, fig.height=5}
keyvals <- ifelse(
   markers.SCvsCHB$avg_log2FC < -0.5 & markers.SCvsCHB$p_val_adj < 0.05, 'green3',
   ifelse(markers.SCvsCHB$avg_log2FC > 0.5 & markers.SCvsCHB$p_val_adj < 0.05, 'orange2',
   'grey50'))
keyvals[is.na(keyvals)]<-'grey50'
names(keyvals)[keyvals == 'orange2'] <- 'Up-regulated SC'
names(keyvals)[keyvals == 'green3'] <- 'Up-regulated CHB'
names(keyvals)[keyvals == 'grey50'] <- 'Not significant'

p2 <- EnhancedVolcano(markers.SCvsCHB , 
                rownames(markers.SCvsCHB ),
                x ="avg_log2FC", 
                y ="p_val_adj",
                pCutoff = 0.05,
                FCcutoff = 0.5,
                title = "Volcano plot SC vs CHB",
                legendPosition = "right",
                lab = NA,
                subtitle = NULL,
                gridlines.minor = FALSE, gridlines.major = FALSE,
                #selectLab = rownames(markers.SCvsr6[which(names(keyvals) %in% c('Down-regulated','Up-regulated'))]),
                colCustom = keyvals)
p2
```

```{r r6vsCHBplot, fig.width=7, fig.height=5}
keyvals <- ifelse(
   markers.HB2vsCHB$avg_log2FC < -0.5 & markers.HB2vsCHB$p_val_adj < 0.05, 'green3',
   ifelse(markers.HB2vsCHB$avg_log2FC > 0.5 & markers.HB2vsCHB$p_val_adj < 0.05, 'blue3',
   'grey50'))
keyvals[is.na(keyvals)]<-'grey50'
names(keyvals)[keyvals == 'blue3'] <- 'Up-regulated HB2'
names(keyvals)[keyvals == 'green3'] <- 'Up-regulated CHB'
names(keyvals)[keyvals == 'grey50'] <- 'Not significant'

p3 <- EnhancedVolcano(markers.HB2vsCHB , 
                rownames(markers.HB2vsCHB ),
                x ="avg_log2FC", 
                y ="p_val_adj",
                pCutoff = 0.05,
                FCcutoff = 0.5,
                title = "Volcano plot HB2 vs CHB",
                legendPosition = "right",
                lab = NA,
                subtitle = NULL,
                gridlines.minor = FALSE, gridlines.major = FALSE,
                #selectLab = rownames(markers.SCvsr6[which(names(keyvals) %in% c('Down-regulated','Up-regulated'))]),
                colCustom = keyvals)
p3
```

```{r combinedPlot, fig.width=25, fig.height=7}
p <- p1 + p2 + p3 + patchwork::plot_layout(guides = "collect")
p
ggsave(filename = "Plots/HB10_SCvsCHBvsHB2_volcanoPlots.png", width = 25, height = 7, plot = p)
saveRDS(p, file = "Plots/HB10_volcanoPlots.RDS")
```

```{r DEgene_xlsx}
DEgenelist <- list()
DEgenelist[["E10_SCvsHB2"]] <- markers.SCvsHB2
DEgenelist[["E10_HB2vsCHB"]] <- markers.HB2vsCHB
DEgenelist[["E10_SCvsCHB"]] <- markers.SCvsCHB
write.xlsx(DEgenelist, file = "Tables/E10_volcanoPlots_DEgenes_SCvsCHBvsHB2.xlsx", rowNames = T)
```

```{r sessionInfo}
sessionInfo()
```

